=begin
  YCOSPACE的Podfile....
=end

source 'https://github.com/CocoaPods/Specs.git' #引入pod原有的私有库  

target 'YCOSPACE' do
 platform :ios, "8.0"
 pod 'AFNetworking', '3.1.0'
 pod 'YYImage', '1.0.4’
 pod 'TTTAttributedLabel', '2.0.0’
 pod 'SDWebImage', '4.2.3’
 pod 'MJRefresh', '3.1.15.3'
 pod 'MJExtension', '3.0.13'
 pod 'Masonry', '1.1.0’
 pod 'Qiniu', '7.2.3’
 pod 'BlocksKit', '2.2.5’
 pod 'Bugly', '2.5.0’

 pod 'GTSDK', '2.1.0.0-noidfa' # 无 idfa版本

 # 主模块(必须)
 pod 'mob_sharesdk', '4.1.1’

 # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
 pod 'mob_sharesdk/ShareSDKPlatforms/QQ', '4.1.1’
 pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo', '4.1.1’
 pod 'mob_sharesdk/ShareSDKPlatforms/WeChat', '4.1.1’  
 pod 'mob_sharesdk/ShareSDKPlatforms/Copy', '4.1.1’

 pod 'mob_sharesdk/ShareSDKExtension', '4.1.1’
 
end

