source ‘https://github.com/CocoaPods/Specs.git’
platform :ios, ‘7.0’
use_frameworks!
target “YCO SPACE” do
pod 'AFNetworking', '~> 3.1.0'
pod 'YYKit'
pod 'TTTAttributedLabel'
pod 'SDWebImage','~>3.8.2’
pod 'MJRefresh','~>3.1.12’
pod 'MJExtension','~>3.0.13'
pod 'Masonry','~>1.0.2’
pod 'Qiniu', '~> 7.1’
pod 'GTSDK'
pod 'Bugly'

 # 主模块(必须)
 pod 'ShareSDK3', '~> 3.4.2'
 # Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
 pod 'MOBFoundation_IDFA', '~> 2.0.11'
 
 # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
 pod 'ShareSDK3/ShareSDKPlatforms/QQ'
 pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
 pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
 
end